'''
    python DataSturucture
    ---------------------
        list
        tuple
        set
        dictionary

        --> this datastructure using for small scale data

    pandas DataSturucture
    ---------------------
        Series
        DataFrame
        Panel

        --> this datastructure using for big scale data

    COMMANDS FROM INSTALL
    ---------------------

    -> Go to cmd and type :- pip install pandas
    -> pip - pip is python  installer package
    -> pip show pandas - for chacking pandas install aur not
    

'''