'''
    --> set is predefined class
    --> class contains methods
    --> To see the methods, dir() function
    
    dir()
        1. with userscore symbol methods
        2. without userscore sysbol method
'''
print("------METHOD IN SET CLASS---------")

import builtins as b
print(dir(b))              # to display all predefined methods, class etc....

# add() method
# add() is predefined METHOD in set class
# We should ACCESS this method by using set object
# By using this method we can add value to set

