# func + para + return keyword 

def add(a,b):
    c = a + b
    return c


p = int(input("Enter value of A :- "))
q = int(input("Enter value of B :- "))
result = add(p,q)
print("Total( A + B )is :- ",result)

'''
Regarding the return, you cannot find anywhere else this kind of explanantion
result = len(a)  -> function
                 -> Parameterized function
                 -> Having return
'''

